/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chatting;

/**
 *
 * @author Thanh Vi
 */
import java.net.Socket;
import java.net.ServerSocket;
import java.io.*;
import java.util.Vector;
public class ManagerChatter extends javax.swing.JFrame implements Runnable{
      ServerSocket svrSocket = null;
      BufferedReader br=null;
      Thread t;
      Vector<Socket> listSocket = new Vector();
      Vector<String> Name=new Vector();
      BufferedWriter os=null;
      BufferedReader bf=null;
      int start=0;
      
      public ManagerChatter() {
            initComponents();
            this.setSize(608,170);
            int serverPort=Integer.parseInt(txtServerPort.getText());
            try {
                  svrSocket = new ServerSocket(serverPort);
                  this.lbMessage.setText("Mng. Server is running at the port ");
            }
            catch (Exception e) {
            }
            
            t=new Thread(this);
            t.start();
      }
 public int check(String str){
       int stt=0;
       for (int i = 0; i < Name.size(); i++) {
             if(str.equals(Name.get(i))){
                   Name.remove(i);
                   listSocket.remove(i-1);
                   break;
             }
       }return stt;
 }
 @Override
    public void run() {
        while(true) {
            try {
                Socket aStaffSocket = svrSocket.accept();
                if(aStaffSocket!=null) {
                    br = new BufferedReader(new InputStreamReader(aStaffSocket.getInputStream()));
                    String S = br.readLine();
                    int pos = S.indexOf(":");
                    String staffName = S.substring(pos+1);
                    listSocket.add(aStaffSocket);
                    if(staffName!=" Manager")Name.add(staffName);
                    ChatPanel_Server p = new ChatPanel_Server(aStaffSocket, "Manager", staffName,listSocket,Name);
                    p.abc(Name);
                    this.setSize(608,600);
                    jTabbedPane1.add(staffName, p);
                    p.updateUI();
                     t=new Thread(p);
                  t.start();
                }
                Thread.sleep(1000);
            } catch (Exception e) {
            }
        }
    }
    
    

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            a = new javax.swing.JPanel();
            lbMessage = new javax.swing.JLabel();
            txtServerPort = new javax.swing.JTextField();
            jTabbedPane1 = new javax.swing.JTabbedPane();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            a.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manager", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

            lbMessage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            lbMessage.setText("Manager Port");

            txtServerPort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
            txtServerPort.setText("8888");

            javax.swing.GroupLayout aLayout = new javax.swing.GroupLayout(a);
            a.setLayout(aLayout);
            aLayout.setHorizontalGroup(
                  aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aLayout.createSequentialGroup()
                        .addContainerGap(283, Short.MAX_VALUE)
                        .addComponent(lbMessage)
                        .addGap(18, 18, 18)
                        .addComponent(txtServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
            );
            aLayout.setVerticalGroup(
                  aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtServerPort, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(lbMessage))
            );

            jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(ManagerChatter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(ManagerChatter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(ManagerChatter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(ManagerChatter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new ManagerChatter().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JPanel a;
      private javax.swing.JTabbedPane jTabbedPane1;
      private javax.swing.JLabel lbMessage;
      private javax.swing.JTextField txtServerPort;
      // End of variables declaration//GEN-END:variables

}
